require ~'collection/pagination'
require ~'collection/pagination_params'
require ~'collection/collection'
require ~'collection/entry'
require ~'collection/feed'
require ~'collection/links'
require ~'collection/scope'
